# Generated by Django 3.1.3 on 2020-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ipaddress',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
