# Generated by Django 3.1.3 on 2020-12-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ip_address',
        ),
    ]
